//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class damage_type
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Attack_Type_Id { get; set; }
    
        public virtual attack_type attack_type { get; set; }
    }
}
