//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class monster
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int damage_type_id { get; set; }
        public int level { get; set; }
        public int experience { get; set; }
        public int difficulty { get; set; }
        public int health_min { get; set; }
        public int health_max { get; set; }
        public int resistance_ice { get; set; }
        public int resistance_fire { get; set; }
        public int resistance_electric { get; set; }
        public int resistance_poison { get; set; }
        public int resistance_melee { get; set; }
        public int resistance_projectile { get; set; }
    
        public virtual damage_type damage_type { get; set; }
    }
}
