//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamedata
{
    using System;
    using System.Collections.Generic;
    
    public partial class weapon
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int Max_Durability { get; set; }
        public int Max_Damage { get; set; }
        public int Max_Value { get; set; }
        public int Min_Durability { get; set; }
        public int Min_Damage { get; set; }
        public int Min_Value { get; set; }
        public int Weight { get; set; }
        public int Speed { get; set; }
    
        public virtual weapon_types weapon_types { get; set; }
    }
}
